/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEquipoRouteImport } from './routes/admin/equipo'
import { Route as AdminGaleriaRouteImport } from './routes/admin/galeria'
import { Route as AdminGeneralRouteImport } from './routes/admin/general'
import { Route as AdminHorariosRouteImport } from './routes/admin/horarios'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPromocionesRouteImport } from './routes/admin/promociones'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminSeccionesRouteImport } from './routes/admin/secciones'
import { Route as AdminServiciosRouteImport } from './routes/admin/servicios'
import { Route as AdminTestimoniosRouteImport } from './routes/admin/testimonios'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as ApiPublicoImagenSplatRouteImport } from './routes/api-publico-imagen/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipoRoute = AdminEquipoRouteImport.update({
  id: '/admin/equipo',
  path: '/admin/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGaleriaRoute = AdminGaleriaRouteImport.update({
  id: '/admin/galeria',
  path: '/admin/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/admin/general',
  path: '/admin/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/admin/horarios',
  path: '/admin/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocionesRoute = AdminPromocionesRouteImport.update({
  id: '/admin/promociones',
  path: '/admin/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeccionesRoute = AdminSeccionesRouteImport.update({
  id: '/admin/secciones',
  path: '/admin/secciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiciosRoute = AdminServiciosRouteImport.update({
  id: '/admin/servicios',
  path: '/admin/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimoniosRoute = AdminTestimoniosRouteImport.update({
  id: '/admin/testimonios',
  path: '/admin/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicoImagenSplatRoute = ApiPublicoImagenSplatRouteImport.update({
  id: '/api-publico-imagen/$',
  path: '/api-publico-imagen/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin/servicios': typeof AdminServiciosRoute
  '/admin/testimonios': typeof AdminTestimoniosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api-publico-imagen/$': typeof ApiPublicoImagenSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin/servicios': typeof AdminServiciosRoute
  '/admin/testimonios': typeof AdminTestimoniosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api-publico-imagen/$': typeof ApiPublicoImagenSplatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin/servicios': typeof AdminServiciosRoute
  '/admin/testimonios': typeof AdminTestimoniosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api-publico-imagen/$': typeof ApiPublicoImagenSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/equipo'
    | '/admin/galeria'
    | '/admin/general'
    | '/admin/horarios'
    | '/admin/login'
    | '/admin/promociones'
    | '/admin/reset-password'
    | '/admin/secciones'
    | '/admin/servicios'
    | '/admin/testimonios'
    | '/admin/usuarios'
    | '/api-publico-imagen/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/equipo'
    | '/admin/galeria'
    | '/admin/general'
    | '/admin/horarios'
    | '/admin/login'
    | '/admin/promociones'
    | '/admin/reset-password'
    | '/admin/secciones'
    | '/admin/servicios'
    | '/admin/testimonios'
    | '/admin/usuarios'
    | '/api-publico-imagen/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/equipo'
    | '/admin/galeria'
    | '/admin/general'
    | '/admin/horarios'
    | '/admin/login'
    | '/admin/promociones'
    | '/admin/reset-password'
    | '/admin/secciones'
    | '/admin/servicios'
    | '/admin/testimonios'
    | '/admin/usuarios'
    | '/api-publico-imagen/$'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEquipoRoute: typeof AdminEquipoRoute
  AdminGaleriaRoute: typeof AdminGaleriaRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPromocionesRoute: typeof AdminPromocionesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSeccionesRoute: typeof AdminSeccionesRoute
  AdminServiciosRoute: typeof AdminServiciosRoute
  AdminTestimoniosRoute: typeof AdminTestimoniosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ApiPublicoImagenSplatRoute: typeof ApiPublicoImagenSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipo': {
      id: '/admin/equipo'
      path: '/admin/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AdminEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/galeria': {
      id: '/admin/galeria'
      path: '/admin/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AdminGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/general': {
      id: '/admin/general'
      path: '/admin/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/admin/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promociones': {
      id: '/admin/promociones'
      path: '/admin/promociones'
      fullPath: '/admin/promociones'
      preLoaderRoute: typeof AdminPromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/secciones': {
      id: '/admin/secciones'
      path: '/admin/secciones'
      fullPath: '/admin/secciones'
      preLoaderRoute: typeof AdminSeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicios': {
      id: '/admin/servicios'
      path: '/admin/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AdminServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonios': {
      id: '/admin/testimonios'
      path: '/admin/testimonios'
      fullPath: '/admin/testimonios'
      preLoaderRoute: typeof AdminTestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-publico-imagen/$': {
      id: '/api-publico-imagen/$'
      path: '/api-publico-imagen/$'
      fullPath: '/api-publico-imagen/$'
      preLoaderRoute: typeof ApiPublicoImagenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEquipoRoute: AdminEquipoRoute,
  AdminGaleriaRoute: AdminGaleriaRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPromocionesRoute: AdminPromocionesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSeccionesRoute: AdminSeccionesRoute,
  AdminServiciosRoute: AdminServiciosRoute,
  AdminTestimoniosRoute: AdminTestimoniosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ApiPublicoImagenSplatRoute: ApiPublicoImagenSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
